spring:
  application:
    name: spring-boot-kafka-backend

  datasource:
    url: jdbc:mysql://localhost:3306/workshop?createDatabaseIfNotExist=true
    username: workshop
    password: workshop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.github.joxebus.dto

server:
  port: 8081
